# Generated by Django 5.0.2 on 2024-03-03 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '类别信息',
                'verbose_name_plural': '类别信息',
                'db_table': 'db_category',
            },
        ),
        migrations.CreateModel(
            name='UserInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'db_user_info',
            },
        ),
        migrations.CreateModel(
            name='GoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('image', models.ImageField(max_length=300, upload_to='', verbose_name='图片')),
                ('content', models.TextField(verbose_name='介绍')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.categorymodel', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '商品信息',
                'verbose_name_plural': '商品信息',
                'db_table': 'db_good',
            },
        ),
        migrations.CreateModel(
            name='HotModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.goodmodel', verbose_name='热门商品')),
            ],
            options={
                'verbose_name': '热门商品',
                'verbose_name_plural': '热门商品',
                'db_table': 'db_hot',
            },
        ),
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='评分')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.goodmodel', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '评分信息',
                'verbose_name_plural': '评分信息',
                'db_table': 'db_rating',
            },
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_buy', models.BooleanField(default=False, verbose_name='是否购买')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.goodmodel', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '用户订单',
                'verbose_name_plural': '用户订单',
                'db_table': 'db_order',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.goodmodel', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '评论信息',
                'verbose_name_plural': '评论信息',
                'db_table': 'db_comment',
            },
        ),
        migrations.CreateModel(
            name='CollectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.goodmodel', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '收藏信息',
                'verbose_name_plural': '收藏信息',
                'db_table': 'db_collect',
            },
        ),
    ]
