# Generated by Django 5.0.2 on 2024-04-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shoppingcarmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='gender',
            field=models.CharField(default='未知', max_length=2, verbose_name='性别相关'),
        ),
        migrations.AddField(
            model_name='userinfomodel',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='userinfomodel',
            name='gender',
            field=models.CharField(default='未知', max_length=2, verbose_name='性别'),
        ),
        migrations.CreateModel(
            name='GoodActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=2, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('action', models.CharField(max_length=10, verbose_name='操作')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.categorymodel', verbose_name='所属分类')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.goodmodel', verbose_name='所属商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.userinfomodel', verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '交互信息',
                'verbose_name_plural': '交互信息',
                'db_table': 'db_action',
            },
        ),
    ]
